### ISSUE TITLE
Mechanism for forcing a command executor to fail.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/testkit#233]
There's currently no way to force the executor obtained from [`Test.CommandExecutor()`](https://pkg.go.dev/github.com/dogmatiq/testkit#Test.CommandExecutor) to produce a non-nil error. This makes it impossible to test failure paths in our gRPC APIs, etc.

We have the same issue with [`Test.EventRecorder()`](https://pkg.go.dev/github.com/dogmatiq/testkit#Test.EventRecorder), although that is used far less often. Assume that any solutions discussed here would apply to the event recorder as well.

/cc @mrubiosan

### Solution 1 - Functional options

Without having given it too much thought, one appropriate approach would be adding [functional options](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis) to [`Call()`](https://pkg.go.dev/github.com/dogmatiq/testkit#Call) and an option that causes the executor to return an error.

The new signature of `Call()` would become:

```go
func Call(fn func(), options ...CallOption) Action { ...
```

Usage would look something like:

```go
test.Expect(
    Call(
        func(...) { ... },
        ForceCommandExecutorToFail(someError), 
    ),
    ToExecuteCommand( ... ),
)
```

This approach keeps the forced-error scoped to a single expectation.  *Maybe* this new option could also implement the `TestOption` interface so that this behaviour can be specified for the lifetime of an entire `Test`, not just a single `Call()`.

### Solution 2 - New methods on `Test`

We could add a method something like `Test.ForceCommandExecutorToFail(error)`.

Usage would be:

```go
test.ForceCommandExecutorToFail(someError)
test.Expect(
    Call(func(...) { ... }),
    ToExecuteCommand( ... ),
)
```

This feels lest robust to me, since you are only allowed to use the command executor inside the function passed to `Call()`, anyway. That said, we do have some precedent for methods like this, such as [`Test.EnableHandlers()`](https://pkg.go.dev/github.com/dogmatiq/testkit#Test.EnableHandlers).

**Comment by jmalloc** [comment]
I think I prefer the "functional option" approach (solution 1 above) but rather than just specifying the error to return, we could instead allow the user to provide a function that "intercepts" the call to the command executor. This lets the user introduce any complex behavior that might be necessary during their test, somewhat akin to a partial mock.

Example usage:

```go
test.Expect(
    Call(
        func(...) { ... },
        WithCommandExecutorBehavior(
                func(actualExecutor dogma.CommandExecutor) error {
                    return errors.New("forced error")
                }, 
        ),
    ),
    ToExecuteCommand( ... ),
)
```

**Comment by danilvpetrov** [comment]
I am leaning towards the first solution above, it seems cleaner and more relevant as an option to  `Call()` as opposed to a separate method on the `test` instance.

**Comment by jmalloc** [comment]
This issue resulted in the addition of two new options - `InterceptCommandExecutor()` and `InterceptEventRecorder()`. These options can be used either at the scope of a single `Call()` action (preferred), or test-wide, if need be, by passing them to `testkit.Begin()`.

Changes have been tagged in https://github.com/dogmatiq/testkit/releases/tag/v0.13.5.
