### ISSUE TITLE
Consider adding an `AdvanceTimeToNextDay()` method.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/testkit#42]

**Comment by jmalloc** [comment]
@koden-km do you think you'd use this in your example tests for "business day" type things?

**Comment by koden-km** [comment]
Hmm maybe. Probably only if not using an accelerated auto ticking time.

**Comment by jmalloc** [comment]
The accelerated time wont affect tests written with testkit - it's only used when you use the `engine` "subpackage" on its own, like you do in the example UI.

**Comment by jmalloc** [comment]
Replaced by #110
