### ISSUE TITLE
Notes on test framework output.

### ISSUE THREAD

**Issue by jmalloc** [dogmatiq/testkit#8]
- Incorrect message content might be from missing branch in `AggregateRoot.ApplyEvent()` implementation. -- Potential "suggestion case" could be when:
    - you're asserting an event was recorded
    - that event *was* recorded but with incorrect content
    - the event came from an aggregate
    - that specific aggregate instance was engaged inside a `prepare` phase
    - any `ApplyEvent()` call involved in that prepare phase did not change the root

Update: @koden-km  had a similar issue when he had a test asserting that an event was **not** recorded, but in fact it was recorded because of a missing branch in `ApplyEvent()`.

**Comment by jmalloc** [comment]
When an aggregate or process attempts to route a message to an empty instance ID, it would be useful to see information about the message being routed, such as its type and the handler/instance that produced it, if any.

The error message at the moment doesn't have much information:

> panic: the 'acquire' process message handler attempted to route a message to an empty instance ID

**Comment by jmalloc** [comment]
> Update: @koden-km had a similar issue when he had a test asserting that an event was **not** recorded, but in fact it was recorded because of a missing branch in `ApplyEvent()`.

It might also be useful to be able to print diffs of aggregate/process root state before/after each message.

**Comment by koden-km** [comment]
I created a branch in the example repo to keep one of the test errors i was getting:
https://github.com/dogmatiq/example/blob/broken-tests-for-improvements/customer/customer.go#L17

**Comment by koden-km** [comment]
It woudl be good to have better test handling of `dogma.unexpectedMessage`.

```
=== RUN   Test_Transfer
=== RUN   Test_Transfer/when_transfer_with_sufficient_funds
=== RUN   Test_Transfer/when_transfer_with_sufficient_funds/it_transfers_the_funds_from_one_account_to_another
panic: (dogma.unexpectedMessage) (0x56a4c0,0x6f9080) [recovered]
	panic: (dogma.unexpectedMessage) (0x56a4c0,0x6f9080)

goroutine 24 [running]:
testing.tRunner.func1(0xc0000cb400)
	/usr/local/go/src/testing/testing.go:830 +0x388
panic(0x56a4c0, 0x6f9080)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/dogmatiq/example/domain.AccountHandler.RouteCommandToInstance(0x57c720, 0xc000131860, 0x0, 0xc0000db7a8)
	/home/kevin/grit/github.com/dogmatiq/example/domain/account.go:84 +0x60a
github.com/dogmatiq/testkit/engine/controller/aggregate.(*Controller).Handle(0xc000026dc0, 0x5d2e80, 0xc00001a160, 0x5cff20, 0xc0001ac900, 0xbf4169db24cb9ec6, 0x2568c6, 0x6ddd40, 0xc000182d20, 0xc00000e4b0, ...)
	/home/kevin/go/pkg/mod/github.com/dogmatiq/testkit@v0.0.0-20190417003242-a42b8582cc6b/engine/controller/aggregate/controller.go:67 +0xdf
github.com/dogmatiq/testkit/engine.(*Engine).handle(0xc000026d40, 0x5d2e80, 0xc00001a160, 0xc0001844c0, 0xc000182d20, 0x5d3600, 0xc000026dc0, 0x0, 0x0, 0x0, ...)
	/home/kevin/go/pkg/mod/github.com/dogmatiq/testkit@v0.0.0-20190417003242-a42b8582cc6b/engine/engine.go:279 +0x25e
github.com/dogmatiq/testkit/engine.(*Engine).dispatch(0xc000026d40, 0x5d2e80, 0xc00001a160, 0xc0001844c0, 0xc00000e4b8, 0x0, 0x0, 0x2568c6, 0x6ddd40)
	/home/kevin/go/pkg/mod/github.com/dogmatiq/testkit@v0.0.0-20190417003242-a42b8582cc6b/engine/engine.go:232 +0x32e
github.com/dogmatiq/testkit/engine.(*Engine).Dispatch(0xc000026d40, 0x5d2e80, 0xc00001a160, 0x583480, 0xc000184440, 0xc000184480, 0x5, 0x8, 0x8, 0xc0000dbd50)
	/home/kevin/go/pkg/mod/github.com/dogmatiq/testkit@v0.0.0-20190417003242-a42b8582cc6b/engine/engine.go:180 +0x3d9
github.com/dogmatiq/testkit.(*Test).dispatch(0xc0000c6680, 0x583480, 0xc000184440, 0x0, 0x0, 0x0, 0x5d2f40, 0xc0000adc20)
	/home/kevin/go/pkg/mod/github.com/dogmatiq/testkit@v0.0.0-20190417003242-a42b8582cc6b/test.go:139 +0xd1
github.com/dogmatiq/testkit.(*Test).ExecuteCommand(0xc0000c6680, 0x583480, 0xc000184440, 0x5d2f40, 0xc0000adc20, 0x0, 0x0, 0x0, 0xc0000c6680)
	/home/kevin/go/pkg/mod/github.com/dogmatiq/testkit@v0.0.0-20190417003242-a42b8582cc6b/test.go:54 +0xb0
github.com/dogmatiq/example/domain_test.Test_Transfer.func1.1(0xc0000cb400)
	/home/kevin/grit/github.com/dogmatiq/example/domain/transfer_test.go:38 +0x5ed
testing.tRunner(0xc0000cb400, 0x5a7fa8)
	/usr/local/go/src/testing/testing.go:865 +0xc0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x357
```

**Comment by koden-km** [comment]
I just got bitten by that `unexpectedMessage` again. I forgot to add a `RouteEventToInstance(...)` case for an event that I declared I would handle in the call to `c.ConsumesEvent(...)`. It took me a while to figure out what was wrong. If testkit can catch those panic's and suggest checking the declared ConsumeXXX/ProduceXXX with actual implementation of RouteXXX/HandleXXX.

**Comment by jmalloc** [comment]
This issue has been split out into separate issues #28, #29, #30 and #31.
